add coturn to synapse
chaos-jetzt/chaos-jetzt-ansible pull request #23
Opened 2020-07-30 11:37 UTC by n0emis

this allows users on this matrix-hs to participate in (video)-calls

2020-07-30 13:30 UTC, leona-ya requested changes
I think the port allow-rule in firewalld is missing (add to `firewall_ports` variable)

2020-08-01 19:15 UTC, leona-ya approved these changes
LGTM, but I would like to wait until the conference on next week Sunday with merging

2020-08-06 16:44 UTC, e1mo requested changes

2020-08-06 16:44 UTC, e1mo commented on group_vars/all.yml
> +  - "turn:turn.chaos.jetzt:3479?transport=udp"
Please use variables

2020-08-06 16:44 UTC, e1mo commented on group_vars/all.yml
> +  - "turn:turn.chaos.jetzt:3479?transport=tcp"
Same here

2020-08-06 16:44 UTC, e1mo commented on group_vars/all.yml
> +coturn_realm: "turn.chaos.jetzt"
And here

2020-08-06 16:44 UTC, e1mo commented on group_vars/all.yml
> +traefik_version: "v2.2.8"
Same goes here

2020-08-06 16:44 UTC, e1mo commented on group_vars/all.yml
> +riot_version: "1.7.2"
I would not mix multiple topics in one PR

2020-08-06 16:44 UTC, e1mo commented on group_vars/all.yml
> +synapse_pip_version: "1.18.0"
Is it required for calls? Otherwise I would not mix multiple topics in one PR

2020-08-09 18:29 UTC, closed without merging