SSO: Install Keycloak & LDAP
chaos-jetzt/chaos-jetzt-ansible pull request #29
Opened 2020-08-14 13:49 UTC by n0emis

This PR installs Keycloak and slapd for usage as a SSO.

Closes #4

2020-08-14 15:28 UTC, n0emis commented
This is already deployed on dev at https://sso.dev.chaos.jetzt

2020-08-15 11:21 UTC, leona-ya approved these changes

2020-08-16 14:08 UTC, e1mo requested changes

2020-08-16 14:08 UTC, e1mo commented on playbooks/site.yml
> +  tags: pretix,matrix,keycloak
```suggestion
  tags:
    - pretix
    - matrix
    - keycloak
```

2020-08-16 14:08 UTC, e1mo commented on templates/traefik/dynamic/keycloak.yml
> +      rule: "Host(`sso.{{ base_url }}`)"
```suggestion
      rule: "Host(`{{ keycloak_url }}`)"
```

2020-08-16 14:08 UTC, e1mo commented on templates/traefik/dynamic/keycloak.yml
> +      rule: "Host(`sso.{{ base_url }}`)"
```suggestion
      rule: "Host(`{{ keycloak_url }}`)"
```

2020-08-16 14:08 UTC, e1mo commented on group_vars/all/keycloak.yml
> +keycloak_http_port: 8081
```suggestion
keycloak_url: "sso.{{ base_url }}"
keycloak_http_port: 8081
```

2020-08-16 14:16 UTC, e1mo approved these changes

2020-08-19 10:25 UTC, merged