Update to Matrix 1.67.0
chaos-jetzt/chaos-jetzt-ansible pull request #62
Opened 2022-09-06 18:53 UTC by e1mo

**This has not been tested on dev yet.** Due to the python3.7 requirement introduced in v1.50 an upgrade on our dev host (Ubuntu 18.04 LTS, python 3.6) requires more time than I have right now. However, prod is running on Debian 10 / python 3.7 that is fine. I would strongly prefer testing this before rolling the update out to production. However, after reading the upgrade notes I do not see any significant difficulties coming. Depending on how you see it, I think we could give directly going to production a try (Of course doing proper procedure with backups before hand and making synapse unreachable until we are assured that nothing obvious broke).

From reading the change log / upgrade notes, those changes seem as if they could affect us (but in the end don't).

- v1.64.0
        - Deprecation of the ability to delegate e-mail verification to identity servers: Should not affect us (I think) due to our usage of SSO
- v1.60.0
        - Possibility for failing migrations if the database is corrupted and has duplicates: We [should be fine](https://github.com/matrix-org/synapse/issues/11779#issuecomment-1131545970) since we don't appear to have any dupes (on prod, not tested on dev):
```sql
SELECT COUNT(1) from ( SELECT state_group, prev_state_group FROM state_group_edges GROUP BY state_group, prev_state_group HAVING COUNT(ctid) > 1 ) AS dupes;
 count
-------
     0
(1 row)
```
- v1.50
        - Python 3.7 and PostgresQL 10+ requirement: Fine in prod, dev runns on Python 3.6

2022-09-06 19:25 UTC, n0emis commented
This will break with 1.64, you'd also have to remove `account_threepid_delegates` from the synapse config

2022-09-19 18:30 UTC, n0emis requested changes
Please update the synapse role to https://github.com/n0emis/ansible-role-synapse/commit/147d40f7cbc70d1e1acc40a6b333cf28a88ae848 (see my comment above)

2022-10-16 13:58 UTC, n0emis approved these changes

2022-10-16 14:01 UTC, leona-ya approved these changes

2023-01-22 14:08 UTC, merged